import type { FoundationConceptId } from '@/content/foundations';

export type ConceptId = 'sources' | 'onelake' | 'lakehouse' | 'warehouse' | 'eventhouse' | 'semantic-model' | 'report';
export type ConceptCategory = 'source' | 'storage' | 'streaming' | 'model' | 'report';
export type Concept = { id: ConceptId; title: string; nodeLabel: string; shortDescription: string; category: ConceptCategory; categoryLabel: string; currentState: string; why: string; tryAction: string; relatedConceptIds: ConceptId[]; objectiveIds: string[]; sourceIds: string[]; keywords: string[]; prerequisiteFoundationIds?: FoundationConceptId[] };
export const concepts: Record<ConceptId, Concept> = {
  sources: { id: 'sources', title: 'Sources', nodeLabel: 'SQL · files · APIs · streams', category: 'source', categoryLabel: 'Source data', shortDescription: 'Operational systems, files, APIs, and streams where Aurora Outfitters data begins.', currentState: 'Order #10482 exists in the operational sales database before analytics ingestion begins.', why: 'Fabric can ingest or access source data. The route should reflect freshness, shape, scale, and workload needs.', tryAction: 'Trace order #10482', relatedConceptIds: ['onelake', 'eventhouse'], objectiveIds: ['PREPARE.GET.CONNECTION', 'PREPARE.GET.INGEST'], sourceIds: ['dp600-guide'], keywords: ['connection', 'ingestion', 'database', 'files', 'stream'], prerequisiteFoundationIds: ['operational-vs-analytical'] },
  onelake: { id: 'onelake', title: 'OneLake', nodeLabel: 'One logical data lake', category: 'storage', categoryLabel: 'Unified storage', shortDescription: 'Fabric’s tenant-wide logical data lake, designed so multiple engines can work over shared data.', currentState: 'Aurora sales data is available through one logical storage layer to multiple Fabric workloads.', why: 'Shared logical storage reduces the need to copy the same data for every analytical engine and experience.', tryAction: 'Follow data into a store', relatedConceptIds: ['lakehouse', 'warehouse', 'eventhouse'], objectiveIds: ['PREPARE.GET.ONELAKE_INTEGRATION'], sourceIds: ['onelake'], keywords: ['storage', 'delta', 'shortcut', 'tenant'], prerequisiteFoundationIds: ['source-to-report-path'] },
  lakehouse: { id: 'lakehouse', title: 'Lakehouse', nodeLabel: 'Files · Delta · Spark + SQL', category: 'storage', categoryLabel: 'Analytics store', shortDescription: 'Combines open file storage and Delta tables with data engineering and SQL access patterns.', currentState: 'Aurora engineers can shape mixed data with Spark while analysts access tables through a SQL analytics endpoint.', why: 'A lakehouse is useful when data engineering and analytics need to meet over open, file-based data.', tryAction: 'Compare storage routes', relatedConceptIds: ['onelake', 'warehouse', 'semantic-model'], objectiveIds: ['PREPARE.GET.STORE_SELECTION'], sourceIds: ['onelake'], keywords: ['spark', 'delta', 'sql analytics endpoint'], prerequisiteFoundationIds: ['operational-vs-analytical'] },
  warehouse: { id: 'warehouse', title: 'Warehouse', nodeLabel: 'Relational · T-SQL · BI', category: 'storage', categoryLabel: 'Analytics store', shortDescription: 'A relational analytics store optimized for T-SQL, governed tables, and enterprise BI workloads.', currentState: 'The current sales trace uses a warehouse to shape order lines into the FactSales star-schema table.', why: 'Structured retail reporting benefits from relational modeling, familiar T-SQL, and warehouse-style analytics.', tryAction: 'Trace the sales transformation', relatedConceptIds: ['onelake', 'lakehouse', 'semantic-model'], objectiveIds: ['PREPARE.GET.STORE_SELECTION', 'PREPARE.QUERY.SQL'], sourceIds: ['onelake'], keywords: ['sql', 'relational', 'fact sales'], prerequisiteFoundationIds: ['sql-kql-dax-overview'] },
  eventhouse: { id: 'eventhouse', title: 'Eventhouse', nodeLabel: 'Events · telemetry · KQL', category: 'streaming', categoryLabel: 'Real-time store', shortDescription: 'A store for high-volume event and telemetry analysis using KQL and real-time intelligence patterns.', currentState: 'Aurora delivery telemetry can flow into Eventhouse without forcing event-shaped data into a relational sales workload.', why: 'Eventhouse fits time-oriented, append-heavy event data that needs low-latency exploration and KQL analysis.', tryAction: 'Compare the three stores', relatedConceptIds: ['onelake', 'warehouse'], objectiveIds: ['PREPARE.GET.STORE_SELECTION', 'PREPARE.QUERY.KQL'], sourceIds: ['eventhouse'], keywords: ['kql', 'telemetry', 'events', 'realtime'], prerequisiteFoundationIds: ['sql-kql-dax-overview'] },
  'semantic-model': { id: 'semantic-model', title: 'Semantic model', nodeLabel: 'Relationships · measures · DAX', category: 'model', categoryLabel: 'Semantic layer', shortDescription: 'A business-ready model that gives data relationships, measures, security, and shared analytical meaning.', currentState: 'FactSales is related to shared dimensions so report filters can produce consistent measures.', why: 'The model separates analytical meaning from individual reports, so calculations and relationships can be reused.', tryAction: 'Trace a report query backward', relatedConceptIds: ['warehouse', 'report'], objectiveIds: ['MODEL.DESIGN.RELATIONSHIPS', 'MODEL.DESIGN.DAX'], sourceIds: ['semantic-models'], keywords: ['dax', 'relationships', 'measure', 'model'], prerequisiteFoundationIds: ['joins-and-relationships', 'star-schema'] },
  report: { id: 'report', title: 'Report', nodeLabel: 'Visuals · filters · decisions', category: 'report', categoryLabel: 'Consumer experience', shortDescription: 'An interactive analytical view that queries the semantic model rather than owning the business logic itself.', currentState: 'The sales visual asks the semantic model for revenue under its current product and region filters.', why: 'A report is the visible consumer of the model. Tracing backward reveals which layers answer its query.', tryAction: 'Trace this query backward', relatedConceptIds: ['semantic-model'], objectiveIds: ['MODEL.OPTIMIZE.QUERY'], sourceIds: ['semantic-models'], keywords: ['visual', 'filter', 'power bi'], prerequisiteFoundationIds: ['refresh-cache-live-query'] },
};
