export type PracticeChoice = { id: string; label: string; feedback: string };

export type JourneyPractice = {
  workedExample: { title: string; instruction: string; observation: string };
  guided: { mission: string; hint: string; choices: PracticeChoice[]; answerId: string; debrief: string };
  independent: { mission: string; choices: PracticeChoice[]; answerId: string; debrief: string };
};

const choice = (id: string, label: string, feedback: string): PracticeChoice => ({ id, label, feedback });

export const journeyPractice: Record<string, JourneyPractice> = {
  'question-orientation': {
    workedExample: { title: 'Watch the trace', instruction: 'In the Fabric Atlas, choose “Trace order #10482” and step from the source to the report.', observation: 'The report consumes a semantic-model result; the order begins in an operational source system.' },
    guided: { mission: 'Aurora needs the source rows available for analytics. Which description means Fabric is ingesting them?', hint: 'Look for data being copied into an analytical store, rather than queried where it currently lives.', choices: [choice('ingest', 'Copy source data into a Fabric store for analytics', 'That is ingestion: a Fabric process brings source data into its analytical environment.'), choice('access', 'Read the operational database in place without bringing its data into a Fabric store', 'That describes access in place, not ingestion.'), choice('visual', 'Add a report visual over an existing semantic model', 'That happens downstream of ingestion and does not move source data.')], answerId: 'ingest', debrief: 'The deciding distinction is whether data enters a Fabric analytical store or remains where it started.' },
    independent: { mission: 'A new supplier API is queried only when an analyst opens a report; Aurora does not persist its data in OneLake. Which relationship to the source is this?', choices: [choice('access', 'Access the source in place', 'Yes. The source remains external and is read when needed.'), choice('ingest', 'Ingest the source into OneLake first', 'That would create a stored analytical copy, which the scenario explicitly excludes.'), choice('transform', 'Transform a stored FactSales table', 'Transformation changes data after it has been brought into the analytical flow.')], answerId: 'access', debrief: 'Ingest and access are not competing labels for the same behavior: one creates an analytical copy; the other reads an existing source.' },
  },
  'choose-store': {
    workedExample: { title: 'Watch the store fit move', instruction: 'In Data Store Lab, keep the retail-reporting workload selected, then change it to streaming telemetry with KQL.', observation: 'Warehouse fits structured T-SQL reporting; Eventhouse becomes the strong fit for high-volume event analysis.' },
    guided: { mission: 'Priya has structured sales tables, batch loading, enterprise BI, and a T-SQL-heavy team. Where should she begin?', hint: 'Match structured relational reporting and T-SQL to the store purpose.', choices: [choice('warehouse', 'Warehouse', 'Warehouse is the strong fit for this relational, T-SQL-oriented BI workload.'), choice('eventhouse', 'Eventhouse', 'Eventhouse is aimed at event and telemetry analysis with KQL, not this reporting workload.'), choice('lakehouse', 'Lakehouse', 'Lakehouse can be useful, but the stated relational BI and T-SQL needs make Warehouse the stronger fit.')], answerId: 'warehouse', debrief: 'The workload requirements decide the fit; no store is universally best.' },
    independent: { mission: 'Aurora now needs to aggregate millions of device events by time window with KQL and very low latency. Which store is the strongest fit?', choices: [choice('eventhouse', 'Eventhouse', 'Yes. The event shape, time-oriented analysis, low latency, and KQL all point here.'), choice('warehouse', 'Warehouse', 'Warehouse fits relational analytics, not the primary event and KQL workload described.'), choice('lakehouse', 'Lakehouse', 'Lakehouse supports broad engineering work, but it is not the strongest match for this real-time event scenario.')], answerId: 'eventhouse', debrief: 'Changing data shape, latency, and language changes the architecture recommendation.' },
  },
  'clean-and-shape': {
    workedExample: { title: 'Watch the quality signals', instruction: 'In Transformation Workbench, remove the duplicate and correct the date type. Inspect the before/after preview after each step.', observation: 'Each operation addresses one data-quality issue; a duplicate and a missing value are not the same problem.' },
    guided: { mission: 'Two rows share the same duplicated order line. Which upstream operation addresses that specific issue?', hint: 'Choose the operation that changes duplicate rows, not the operation that changes a column value.', choices: [choice('duplicates', 'Remove duplicate', 'Yes. This removes repeated records according to the defined duplicate columns.'), choice('null', 'Replace null', 'Replacing null addresses a missing value, but it leaves duplicate records intact.'), choice('type', 'Change type', 'Changing a type does not remove a repeated row.')], answerId: 'duplicates', debrief: 'Data-quality fixes are specific: identify the property that is wrong before choosing the transformation.' },
    independent: { mission: 'OrderDate includes both dates and text values such as “03/08/26”. Before grouping sales by month, what is the appropriate first operation?', choices: [choice('type', 'Change OrderDate to a date type', 'Yes. Date grouping and comparisons need a consistent date type.'), choice('aggregate', 'Aggregate revenue immediately', 'Aggregation before resolving the date type can group inconsistent values incorrectly.'), choice('duplicate', 'Remove duplicate', 'Duplicates may be a separate issue, but they do not make date values comparable.')], answerId: 'type', debrief: 'Transform data upstream so all downstream reports receive a consistent representation.' },
  },
  'build-star-schema': {
    workedExample: { title: 'Watch repeated detail move', instruction: 'In Schema Lab, move product and store attributes into their dimensions. Keep the order-line measures in FactSales.', observation: 'The fact table keeps its defined grain; descriptive attributes become reusable dimensions.' },
    guided: { mission: 'ProductCategory repeats on many sales rows and is used to group revenue. Where does it belong?', hint: 'Ask whether it describes an entity or records the measured sales event.', choices: [choice('dimension', 'DimProduct', 'Yes. ProductCategory describes a product and is used to filter or group facts.'), choice('fact', 'FactSales', 'FactSales records order-line events and measures; keeping repeated product attributes there preserves the wide operational shape.'), choice('measure', 'A DAX measure', 'A category is descriptive data, not a calculation over filter context.')], answerId: 'dimension', debrief: 'Dimensions describe entities for filtering and grouping; facts record measurable events.' },
    independent: { mission: 'Aurora adds one shipping-fee row per order to FactSales, which currently has one row per order line. What is the modeling concern?', choices: [choice('grain', 'The table now mixes grains', 'Yes. One row per order and one row per order line are different levels of detail.'), choice('cardinality', 'The table must be many-to-many', 'Cardinality is about links between tables; the issue here is the level represented by each row.'), choice('format', 'The numeric format is wrong', 'Formatting cannot resolve mixed levels of detail.')], answerId: 'grain', debrief: 'Define a fact table’s grain before adding measures, or totals can silently misstate the business.' },
  },
  'model-relationships': {
    workedExample: { title: 'Watch a filter travel', instruction: 'In Relationship Lab, filter to a region, then compare single-direction and bidirectional filtering.', observation: 'The dimension filter reaches FactSales in the allowed direction; both directions can create extra paths.' },
    guided: { mission: 'What relationship direction should Elena start with for DimRegion → FactSales?', hint: 'Start with the least complex path that lets a descriptive dimension filter its facts.', choices: [choice('single', 'Single direction from DimRegion to FactSales', 'Yes. This is the standard, predictable star-schema path.'), choice('both', 'Both directions by default', 'Bidirectional filtering can be required in a deliberate pattern, but it adds propagation paths that are unnecessary here.'), choice('none', 'No relationship', 'Without a relationship, the region filter cannot affect sales rows.')], answerId: 'single', debrief: 'Use simple one-to-many, single-direction relationships by default; add complexity only for a specific reason.' },
    independent: { mission: 'Several customers can use several accounts, and balances must not be duplicated. What model pattern fits?', choices: [choice('bridge', 'Customer → bridge table → Account → FactBalance', 'Yes. The bridge represents the shared associations without duplicating balance facts.'), choice('direct', 'Directly relate FactBalance to DimCustomer many-to-many', 'This hides the business association and risks ambiguous filtering.'), choice('duplicate', 'Copy each balance for every customer', 'Duplicating facts would overstate totals.')], answerId: 'bridge', debrief: 'A bridge table models a genuine many-to-many association while preserving the fact table’s values.' },
  },
  'add-a-measure': {
    workedExample: { title: 'Watch context change', instruction: 'In DAX Microscope, step through the CALCULATE scenario with the Region filter visible.', observation: 'CALCULATE adds the Bike filter, then the relationship limits the fact rows; the existing Region filter remains.' },
    guided: { mission: 'Marta filters the report to Norway. CALCULATE then adds Category = Bike. Which filter should remain?', hint: 'Only a filter CALCULATE explicitly changes is replaced or removed in this scenario.', choices: [choice('region', 'The Norway filter remains active', 'Yes. CALCULATE adds the category condition without clearing Region.'), choice('none', 'All filters are cleared', 'CALCULATE does not clear every filter by default.'), choice('category', 'Only the category filter remains', 'That would require removing Region, which the expression does not do.')], answerId: 'region', debrief: 'Trace the complete filter context after CALCULATE, rather than treating it as a reset button.' },
    independent: { mission: 'An expression uses ALL(DimProduct) while Region = Norway is already active. What changes?', choices: [choice('product', 'Product filters are removed; Norway remains', 'Yes. ALL targets DimProduct, not every table in the model.'), choice('all', 'Every report filter is removed', 'ALL removes filters only from the table or column it is given.'), choice('region', 'Only the Norway filter is removed', 'Region is not the argument to ALL in this expression.')], answerId: 'product', debrief: 'DAX filter functions are scoped. Name the table or column they touch, then inspect what remains.' },
  },
  'trace-the-query': {
    workedExample: { title: 'Watch the route reroute', instruction: 'In Storage Mode Lab, run the same report query in Import and DirectQuery, then select Direct Lake.', observation: 'The same visual can be answered from imported memory, a source query, or required OneLake columns depending on model mode.' },
    guided: { mission: 'Which mode uses data copied into the model during refresh, then answers report queries from that in-memory copy?', hint: 'Separate a scheduled model refresh from a live source query.', choices: [choice('import', 'Import', 'Yes. Import copies data during refresh and serves queries from the model.'), choice('directquery', 'DirectQuery', 'DirectQuery sends each request to the source rather than relying on an imported model copy.'), choice('directlake', 'Direct Lake', 'Direct Lake loads required Delta-table columns from OneLake for query execution; it is not traditional Import refresh.')], answerId: 'import', debrief: 'Storage mode is a query-path decision with freshness and performance consequences.' },
    independent: { mission: 'Aurora has large Delta tables in OneLake and needs interactive analytics without a traditional full Import refresh. Which mode is indicated?', choices: [choice('directlake', 'Direct Lake', 'Yes. These clues point to Direct Lake over OneLake-backed Delta tables.'), choice('import', 'Import', 'Import uses a copied model refreshed on a schedule, contrary to the key requirement.'), choice('directquery', 'DirectQuery', 'DirectQuery queries a source at request time; the OneLake Delta-table requirement points to Direct Lake.')], answerId: 'directlake', debrief: 'Recognize the cluster of requirements: large Delta tables, OneLake, interactive analysis, and no traditional full import refresh.' },
  },
  'control-access': {
    workedExample: { title: 'Watch identity change the result', instruction: 'In Security Lens, switch from a broad-access identity to Norway Sales and inspect the visible report rows.', observation: 'The report can still open, while row-level security filters out Sweden for Jonas.' },
    guided: { mission: 'Jonas can open the report but must never see Sweden’s sales rows. Which layer implements that restriction?', hint: 'The requirement is about which records are visible after the report opens.', choices: [choice('rls', 'Row-level security on the semantic model', 'Yes. RLS filters visible model rows for the active identity.'), choice('workspace', 'A workspace role', 'Workspace access controls capabilities and access to the container, not a region-specific subset of report rows.'), choice('item', 'An item permission', 'Item permission governs whether the report or model can be opened, not which sales rows appear.')], answerId: 'rls', debrief: 'Security names are easy to blur together; identify the layer named by the requirement.' },
    independent: { mission: 'Leila must hide PayrollCost entirely from an analyst who can otherwise query the semantic model. Which control is appropriate?', choices: [choice('ols', 'Object-level security', 'Yes. OLS makes a table or object unavailable to the user.'), choice('rls', 'Row-level security', 'RLS keeps the object available but filters its rows.'), choice('workspace', 'Workspace role', 'Changing workspace role is broader than the object-level requirement.')], answerId: 'ols', debrief: 'RLS controls rows; OLS controls objects; item and workspace permissions control access at higher layers.' },
  },
  'diagnose-performance': {
    workedExample: { title: 'Watch one lever at a time', instruction: 'In Performance Lab, change one recommended model decision, then compare the simulated engine work before and after.', observation: 'The simulated result identifies a causal lever; it is not a generic “make the report faster” score.' },
    guided: { mission: 'A report model stores an unnecessary, high-cardinality customer comment column. What is the most direct improvement?', hint: 'Focus on the source of model-cardinality pressure, not a cosmetic visual adjustment.', choices: [choice('remove', 'Remove the unnecessary high-cardinality column', 'Yes. Reducing irrelevant cardinality reduces model pressure and can improve query work.'), choice('theme', 'Change the report theme', 'A visual theme does not remove cardinality from the model.'), choice('both', 'Make every relationship bidirectional', 'That can add complexity rather than addressing the high-cardinality column.')], answerId: 'remove', debrief: 'Performance symptoms usually have an upstream model, DAX, relationship, or storage cause.' },
    independent: { mission: 'A monthly revenue visual can be answered from a small imported monthly aggregate instead of a 200M-row DirectQuery fact table. What design helps?', choices: [choice('aggregate', 'Use an aggregation table for the monthly query', 'Yes. A suitably designed aggregation can answer the higher-level request without scanning transaction detail.'), choice('detail', 'Force the visual to use transaction detail', 'That retains the expensive route even though the visual only needs monthly totals.'), choice('bidir', 'Enable bidirectional filters everywhere', 'Filter direction does not create an aggregate route and may make the model harder to reason about.')], answerId: 'aggregate', debrief: 'Match the storage and aggregation design to the detail level the query actually needs.' },
  },
};
