export type Source = {
  id: string;
  title: string;
  publisher: 'Microsoft Learn';
  url: string;
  accessed: string;
  appliesTo: string[];
};
export const sources: Record<string, Source> = {
  'dp600-guide': {
    id: 'dp600-guide',
    title: 'Study guide for Exam DP-600',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/credentials/certifications/resources/study-guides/dp-600',
    accessed: '31 Aug 2026',
    appliesTo: ['sources', 'semantic-model', 'report'],
  },
  'dp600-certification': {
    id: 'dp600-certification',
    title: 'Microsoft Certified: Fabric Analytics Engineer Associate',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/fabric-analytics-engineer-associate/',
    accessed: '1 Sep 2026',
    appliesTo: ['exam-prep'],
  },
  'practice-assessments': {
    id: 'practice-assessments',
    title: 'Practice Assessments for Microsoft Certifications',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/practice-assessments-for-microsoft-certifications',
    accessed: '1 Sep 2026',
    appliesTo: ['exam-prep'],
  },
  onelake: {
    id: 'onelake',
    title: 'OneLake, the OneDrive for data',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/onelake/onelake-overview',
    accessed: '31 Aug 2026',
    appliesTo: ['onelake', 'lakehouse', 'warehouse'],
  },
  eventhouse: {
    id: 'eventhouse',
    title: 'Eventhouse overview',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/real-time-intelligence/eventhouse',
    accessed: '31 Aug 2026',
    appliesTo: ['eventhouse'],
  },
  'semantic-models': {
    id: 'semantic-models',
    title: 'Power BI semantic models',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/connect-data/service-datasets-understand',
    accessed: '31 Aug 2026',
    appliesTo: ['semantic-model', 'report'],
  },
  'fabric-storage-options': {
    id: 'fabric-storage-options',
    title: 'Data storage options in Microsoft Fabric',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/fundamentals/store-data',
    accessed: '31 Aug 2026',
    appliesTo: ['lakehouse', 'warehouse', 'eventhouse'],
  },
  'direct-lake-how': {
    id: 'direct-lake-how',
    title: 'How Direct Lake works',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/fundamentals/direct-lake-how-it-works',
    accessed: '31 Aug 2026',
    appliesTo: ['semantic-model', 'onelake'],
  },
  'direct-lake-security': {
    id: 'direct-lake-security',
    title: 'Integrate Direct Lake security',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/fundamentals/direct-lake-security-integration',
    accessed: '7 Sep 2026',
    appliesTo: ['semantic-model', 'security'],
  },
  'semantic-model-modes': {
    id: 'semantic-model-modes',
    title: 'Semantic model modes in the Power BI service',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/connect-data/service-dataset-modes-understand',
    accessed: '31 Aug 2026',
    appliesTo: ['semantic-model', 'storage-modes'],
  },
  'incremental-refresh': {
    id: 'incremental-refresh',
    title: 'Configure incremental refresh and real-time data',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/connect-data/incremental-refresh-overview',
    accessed: '31 Aug 2026',
    appliesTo: ['semantic-model', 'incremental-refresh'],
  },
  'fabric-permission-model': {
    id: 'fabric-permission-model',
    title: 'Permission model',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/security/permission-model',
    accessed: '31 Aug 2026',
    appliesTo: ['security', 'workspace', 'semantic-model'],
  },
  'fabric-endorsement': {
    id: 'fabric-endorsement',
    title: 'Endorsement overview',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/governance/endorsement-overview',
    accessed: '7 Sep 2026',
    appliesTo: ['governance', 'endorsement'],
  },
  'fabric-information-protection': {
    id: 'fabric-information-protection',
    title: 'Information protection in Fabric',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/governance/information-protection',
    accessed: '7 Sep 2026',
    appliesTo: ['governance', 'sensitivity-labels'],
  },
  'fabric-cicd': {
    id: 'fabric-cicd',
    title: 'Introduction to CI/CD in Microsoft Fabric',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/cicd/cicd-overview',
    accessed: '7 Sep 2026',
    appliesTo: ['lifecycle', 'deployment-pipelines', 'git'],
  },
  'onelake-catalog': {
    id: 'onelake-catalog',
    title: 'OneLake catalog overview',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/governance/onelake-catalog-overview',
    accessed: '7 Sep 2026',
    appliesTo: ['discovery', 'governance', 'onelake'],
  },
  'onelake-security': {
    id: 'onelake-security',
    title: 'Data security overview',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/onelake/get-started-security',
    accessed: '31 Aug 2026',
    appliesTo: ['security', 'onelake'],
  },
  'semantic-model-ols': {
    id: 'semantic-model-ols',
    title: 'Object-level security',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/security/service-admin-object-level-security',
    accessed: '31 Aug 2026',
    appliesTo: ['security', 'semantic-model'],
  },
  'optimize-semantic-model': {
    id: 'optimize-semantic-model',
    title: 'Optimize semantic model performance',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/training/modules/optimize-semantic-model-performance/',
    accessed: '31 Aug 2026',
    appliesTo: ['performance', 'semantic-model', 'dax'],
  },
  'field-parameters': {
    id: 'field-parameters',
    title: 'Use field parameters to let report readers change visuals',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/create-reports/power-bi-field-parameters',
    accessed: '31 Aug 2026',
    appliesTo: ['field-parameters', 'semantic-model', 'report'],
  },
  'calculation-groups': {
    id: 'calculation-groups',
    title: 'Create calculation groups',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/transform-model/calculation-groups',
    accessed: '31 Aug 2026',
    appliesTo: ['calculation-groups', 'semantic-model', 'dax'],
  },
  'composite-model-guidance': {
    id: 'composite-model-guidance',
    title: 'Composite model guidance',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/guidance/composite-model-guidance',
    accessed: '31 Aug 2026',
    appliesTo: ['composite-models', 'semantic-model'],
  },
  'prepare-transform-data': {
    id: 'prepare-transform-data',
    title: 'Prepare and transform data in Microsoft Fabric',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/fundamentals/prepare-transform-data',
    accessed: '31 Aug 2026',
    appliesTo: ['transformation'],
  },
  'query-warehouse': {
    id: 'query-warehouse',
    title: 'Query the Warehouse or SQL analytics endpoint',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/data-warehouse/query-warehouse',
    accessed: '31 Aug 2026',
    appliesTo: ['query'],
  },
  'kql-reference': {
    id: 'kql-reference',
    title: 'KQL quick reference',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/kusto/query/kql-quick-reference?view=microsoft-fabric',
    accessed: '31 Aug 2026',
    appliesTo: ['query', 'eventhouse'],
  },
  'star-schema-guidance': {
    id: 'star-schema-guidance',
    title: 'Understand star schema and the importance for Power BI',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/guidance/star-schema',
    accessed: '31 Aug 2026',
    appliesTo: ['schema', 'scd'],
  },
  'composite-models': {
    id: 'composite-models',
    title: 'Use composite models in Power BI Desktop',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/transform-model/desktop-composite-models',
    accessed: '7 Sep 2026',
    appliesTo: ['composite-models', 'semantic-model'],
  },
  'dax-filtering': {
    id: 'dax-filtering',
    title: 'Filter functions (DAX)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/dax/filter-functions-dax',
    accessed: '7 Sep 2026',
    appliesTo: ['dax', 'filtering'],
  },
  'dax-information-functions': {
    id: 'dax-information-functions',
    title: 'Information functions (DAX)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/dax/information-functions-dax',
    accessed: '7 Sep 2026',
    appliesTo: ['dax', 'information-functions'],
  },
  'dax-iterators': {
    id: 'dax-iterators',
    title: 'SUMX function (DAX)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/dax/sumx-function-dax',
    accessed: '7 Sep 2026',
    appliesTo: ['dax', 'iterators'],
  },
  'dax-variables': {
    id: 'dax-variables',
    title: 'VAR keyword (DAX)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/dax/var-dax',
    accessed: '7 Sep 2026',
    appliesTo: ['dax', 'variables', 'performance'],
  },
  'dax-window': {
    id: 'dax-window',
    title: 'WINDOW function (DAX)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/dax/window-function-dax',
    accessed: '7 Sep 2026',
    appliesTo: ['dax', 'window-functions'],
  },
  'dimensional-modeling-facts': {
    id: 'dimensional-modeling-facts',
    title: 'Fact tables in dimensional modeling',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/data-warehouse/dimensional-modeling-fact-tables',
    accessed: '7 Sep 2026',
    appliesTo: ['schema', 'fact-tables'],
  },
  'dimensional-modeling-load': {
    id: 'dimensional-modeling-load',
    title: 'Load tables in dimensional modeling',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/data-warehouse/dimensional-modeling-load-tables',
    accessed: '7 Sep 2026',
    appliesTo: ['schema', 'dimensions', 'fact-tables'],
  },
  'dynamic-format-strings': {
    id: 'dynamic-format-strings',
    title: 'Create dynamic format strings for measures',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/create-reports/desktop-dynamic-format-strings',
    accessed: '7 Sep 2026',
    appliesTo: ['dax', 'dynamic-format-strings'],
  },
  'eventhouse-onelake': {
    id: 'eventhouse-onelake',
    title: 'Eventhouse OneLake availability',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/real-time-intelligence/event-house-onelake-availability',
    accessed: '7 Sep 2026',
    appliesTo: ['eventhouse', 'onelake'],
  },
  'fabric-git-integration': {
    id: 'fabric-git-integration',
    title: 'Introduction to Git integration',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/cicd/git-integration/intro-to-git-integration',
    accessed: '7 Sep 2026',
    appliesTo: ['lifecycle', 'git'],
  },
  'fabric-lineage': {
    id: 'fabric-lineage',
    title: 'Lineage in Fabric',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/governance/lineage',
    accessed: '7 Sep 2026',
    appliesTo: ['governance', 'lineage', 'impact-analysis'],
  },
  'kql-query': {
    id: 'kql-query',
    title: 'Kusto Query Language overview',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/kusto/query/?view=microsoft-fabric',
    accessed: '7 Sep 2026',
    appliesTo: ['query', 'kql', 'eventhouse'],
  },
  'large-semantic-models': {
    id: 'large-semantic-models',
    title: 'Large semantic models in Power BI Premium',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/enterprise/service-premium-large-models',
    accessed: '7 Sep 2026',
    appliesTo: ['semantic-model', 'large-models'],
  },
  'onelake-shortcuts': {
    id: 'onelake-shortcuts',
    title: 'OneLake shortcuts',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/onelake/onelake-shortcuts',
    accessed: '7 Sep 2026',
    appliesTo: ['onelake', 'shortcuts', 'data-access'],
  },
  'performance-analyzer': {
    id: 'performance-analyzer',
    title: 'Use Performance Analyzer to examine report performance',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/create-reports/desktop-performance-analyzer',
    accessed: '7 Sep 2026',
    appliesTo: ['performance', 'report'],
  },
  'powerbi-pbids': {
    id: 'powerbi-pbids',
    title: 'Power BI data source files (PBIDS)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/connect-data/desktop-data-sources',
    accessed: '7 Sep 2026',
    appliesTo: ['pbids', 'reusable-assets'],
  },
  'powerbi-pbip': {
    id: 'powerbi-pbip',
    title: 'Power BI Desktop projects (PBIP)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/developer/projects/projects-overview',
    accessed: '7 Sep 2026',
    appliesTo: ['pbip', 'git', 'lifecycle'],
  },
  'powerbi-report-templates': {
    id: 'powerbi-report-templates',
    title: 'Create and use report templates in Power BI Desktop',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/create-reports/desktop-templates',
    accessed: '7 Sep 2026',
    appliesTo: ['pbit', 'reusable-assets'],
  },
  'realtime-hub': {
    id: 'realtime-hub',
    title: 'Real-Time hub overview',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/real-time-hub/real-time-hub-overview',
    accessed: '7 Sep 2026',
    appliesTo: ['real-time-hub', 'discovery', 'streaming'],
  },
  'semantic-model-permissions': {
    id: 'semantic-model-permissions',
    title: 'Semantic model permissions',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/connect-data/service-datasets-permissions',
    accessed: '7 Sep 2026',
    appliesTo: ['semantic-model', 'permissions', 'reuse'],
  },
  'semantic-model-security': {
    id: 'semantic-model-security',
    title: 'Object-level security',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/security/service-admin-object-level-security',
    accessed: '7 Sep 2026',
    appliesTo: ['semantic-model', 'security', 'ols'],
  },
  'semantic-model-storage-modes': {
    id: 'semantic-model-storage-modes',
    title: 'Semantic model modes in the Power BI service',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/connect-data/service-dataset-modes-understand',
    accessed: '7 Sep 2026',
    appliesTo: ['semantic-model', 'storage-modes'],
  },
  'shared-semantic-models': {
    id: 'shared-semantic-models',
    title: 'Power BI semantic models',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/connect-data/service-datasets-understand',
    accessed: '7 Sep 2026',
    appliesTo: ['semantic-model', 'reuse', 'report'],
  },
  'sql-query-editor': {
    id: 'sql-query-editor',
    title: 'Query using the SQL query editor',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/data-warehouse/sql-query-editor',
    accessed: '7 Sep 2026',
    appliesTo: ['query', 'sql', 'warehouse'],
  },
  'visual-query-editor': {
    id: 'visual-query-editor',
    title: 'Query using the visual query editor',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/fabric/data-warehouse/visual-query-editor',
    accessed: '7 Sep 2026',
    appliesTo: ['query', 'visual-query-editor', 'warehouse'],
  },
  'xmla-endpoint': {
    id: 'xmla-endpoint',
    title: 'Semantic model connectivity with the XMLA endpoint',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/power-bi/enterprise/service-premium-connect-tools',
    accessed: '7 Sep 2026',
    appliesTo: ['xmla', 'semantic-model', 'lifecycle'],
  },
};
