'use client';

import { ArrowLeft, BookOpen, Braces, Check, Grid3X3, Layers3, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { calculationGroupAccuracyNote, calculationItems, evaluateCalculationGroup, formatCalculationValue, repetitiveMeasureNames, type BaseMeasure, type CalculationItem } from '@/engine/calculation-groups/model';

const measures: { id: BaseMeasure; label: string }[] = [{ id: 'sales', label: 'Sales' }, { id: 'margin', label: 'Margin' }, { id: 'orders', label: 'Orders' }];
const items = Object.entries(calculationItems) as [CalculationItem, (typeof calculationItems)[CalculationItem]][];

export function CalculationGroupLab() {
  const [collapsed, setCollapsed] = useState(false);
  const [measure, setMeasure] = useState<BaseMeasure>('sales');
  const [item, setItem] = useState<CalculationItem>('current');
  const result = useMemo(() => evaluateCalculationGroup(measure, item), [measure, item]);
  return <div className="lab-page calc-group-page"><header className="lab-topbar"><a href="#explore" className="lab-back"><ArrowLeft />Fabric Atlas</a><div><strong>Calculation Group Lab</strong><span>Aurora Outfitters · Time intelligence</span></div><span className="simulation-label">Reusable calculation model</span></header><main className="calc-shell">
    <section className="calc-controls" aria-labelledby="calc-title"><p className="eyebrow">Measure design</p><h1 id="calc-title">Collapse repetitive measures</h1><p>Start with twelve separately authored measures. Introduce one calculation group, then apply each reusable item to any explicit base measure.</p><Button onClick={() => setCollapsed(!collapsed)}><Sparkles />{collapsed ? 'Show measure explosion' : 'Introduce calculation group'}</Button>{collapsed ? <><fieldset><legend>Base measure</legend>{measures.map((entry) => <button className={measure === entry.id ? 'active' : ''} key={entry.id} onClick={() => setMeasure(entry.id)}>{entry.label}</button>)}</fieldset><fieldset><legend>Time Intelligence item</legend>{items.map(([id, entry]) => <button className={item === id ? 'active' : ''} key={id} onClick={() => setItem(id)}>{entry.label}</button>)}</fieldset></> : null}<aside><Layers3 /><div><strong>{collapsed ? '3 measures + 4 calculation items' : '3 subjects × 4 variants'}</strong><p>{collapsed ? 'The selected calculation item replaces SELECTEDMEASURE() with the current explicit measure.' : 'Every new subject measure would require another four time variants.'}</p></div></aside></section>
    <section className="calc-stage" aria-labelledby="calc-stage-title"><div className="calc-heading"><div><p className="eyebrow">Model explorer</p><h2 id="calc-stage-title">{collapsed ? 'Reusable calculation applied' : 'Combinatorial repetition'}</h2></div><span>{collapsed ? '7 reusable objects' : '12 separate measures'}</span></div>{!collapsed ? <div className="measure-explosion">{repetitiveMeasureNames.map((name) => <article key={name}><Braces /><strong>{name}</strong><small>Separate DAX measure</small></article>)}</div> : <><div className="collapsed-model"><section><header><Grid3X3 /><strong>Explicit measures</strong></header>{measures.map((entry) => <button className={measure === entry.id ? 'active' : ''} key={entry.id} onClick={() => setMeasure(entry.id)}><span>{entry.label}</span>{measure === entry.id ? <Check /> : null}</button>)}</section><span className="calc-operator">×</span><section><header><Layers3 /><strong>Time Intelligence</strong></header>{items.map(([id, entry]) => <button className={item === id ? 'active' : ''} key={id} onClick={() => setItem(id)}><span>{entry.label}</span>{item === id ? <Check /> : null}</button>)}</section><span className="calc-operator">=</span><article className="calc-result"><small>{result.measureLabel} · {result.itemLabel}</small><strong>{formatCalculationValue(measure, item, result.value)}</strong><span>Numeric result</span></article></div><section className="calc-expression"><header><Braces /><div><small>Calculation item expression</small><strong>{result.itemLabel}</strong></div></header><code>{result.expression}</code><footer><span>Dynamic format string</span><code>{result.formatString}</code></footer></section></>}
      <aside className="calc-observation"><Sparkles /><div><strong>{collapsed ? 'The grid collapsed, not the capability' : 'Repetition grows multiplicatively'}</strong><p>{collapsed ? `${result.itemLabel} is evaluated against ${result.measureLabel}. The format string changes presentation without converting the numeric result to text.` : 'Adding one more base measure would require four more authored variants in this design.'}</p><small>{calculationGroupAccuracyNote}</small></div></aside><footer className="security-source"><span>Current behavior verified with Microsoft Learn</span><a href="https://learn.microsoft.com/en-us/power-bi/transform-model/calculation-groups" target="_blank" rel="noreferrer"><BookOpen />Calculation group guidance</a></footer>
    </section>
  </main></div>;
}
