'use client';

import { ArrowLeft, BookOpen, Boxes, Check, DatabaseZap, FileChartColumn, Gauge, Network, RotateCcw, Sigma, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { evaluatePerformance, explainLastOptimization, optimizations, performanceAccuracyNote, type OptimizationId } from '@/engine/performance/model';

const areaIcons = { Model: Boxes, DAX: Sigma, Relationships: Network, Visual: FileChartColumn };
const formatRows = (value: number) => value >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : `${Math.round(value / 1_000)}K`;

export function PerformanceLab() {
  const [selected, setSelected] = useState<OptimizationId[]>([]);
  const [lastChanged, setLastChanged] = useState<OptimizationId | null>(null);
  const metrics = useMemo(() => evaluatePerformance(selected), [selected]);
  const toggle = (id: OptimizationId) => { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); setLastChanged(id); };
  const reset = () => { setSelected([]); setLastChanged(null); };
  const storageWidth = `${metrics.storageEngineMs / metrics.durationMs * 100}%`;
  const formulaWidth = `${metrics.formulaEngineMs / metrics.durationMs * 100}%`;

  return <div className="lab-page performance-page"><header className="lab-topbar"><a href="#explore" className="lab-back"><ArrowLeft />Fabric Atlas</a><div><strong>Performance Lab</strong><span>Aurora Outfitters · Revenue by category</span></div><span className="simulation-label">Simulated for learning</span></header><main className="performance-shell">
    <section className="performance-controls" aria-labelledby="performance-title"><p className="eyebrow">Optimization bench</p><h1 id="performance-title">Tune the system, not a score</h1><p>The baseline report is intentionally inefficient. Apply changes and connect each consequence to model, DAX, relationship, or visual work.</p><div className="optimization-list">{optimizations.map((optimization) => { const Icon = areaIcons[optimization.area]; const active = selected.includes(optimization.id); return <button key={optimization.id} className={active ? 'active' : ''} onClick={() => toggle(optimization.id)} aria-pressed={active}><span>{active ? <Check /> : <Icon />}</span><div><small>{optimization.area}</small><strong>{optimization.title}</strong><p>{optimization.description}</p></div></button>; })}</div><Button variant="ghost" onClick={reset} disabled={!selected.length}><RotateCcw />Reset baseline</Button></section>
    <section className="performance-stage" aria-labelledby="performance-dashboard-title"><div className="performance-heading"><div><p className="eyebrow">Deterministic query profile</p><h2 id="performance-dashboard-title">{selected.length ? `${selected.length} intervention${selected.length === 1 ? '' : 's'} applied` : 'Inefficient baseline'}</h2></div><span>{metrics.workRatio.toFixed(2)}× baseline work</span></div>
      <div className="performance-metrics"><article className="primary-metric"><Gauge /><span><small>Simulated duration</small><strong>{(metrics.durationMs / 1000).toFixed(2)} s</strong><b>{1840 - metrics.durationMs} ms removed</b></span></article><article><small>Rows scanned</small><strong>{formatRows(metrics.rowsScanned)}</strong><span>detail or aggregate</span></article><article><small>Model size</small><strong>{metrics.modelMb.toLocaleString()} MB</strong><span>cardinality + aggregation</span></article><article><small>Visual work</small><strong>{metrics.visualMs} ms</strong><span>render + interactions</span></article></div>
      <section className="engine-profile"><header><DatabaseZap /><div><small>Query execution split</small><strong>Where the simulated time is spent</strong></div></header><div className="engine-bar" aria-label={`Storage engine ${metrics.storageEngineMs} milliseconds, formula engine ${metrics.formulaEngineMs} milliseconds, visual ${metrics.visualMs} milliseconds`}><span className="storage-work" style={{ width: storageWidth }} /><span className="formula-work" style={{ width: formulaWidth }} /><span className="visual-work" /></div><div className="engine-legend"><span><i className="storage-work" />Storage engine<strong>{metrics.storageEngineMs} ms</strong></span><span><i className="formula-work" />Formula engine<strong>{metrics.formulaEngineMs} ms</strong></span><span><i className="visual-work" />Visual<strong>{metrics.visualMs} ms</strong></span></div></section>
      <div className="performance-system"><section><p className="eyebrow">Model pressure</p><div className="pressure-row"><article className={selected.includes('remove-tracking-id') ? 'is-fixed' : ''}><Boxes /><span><small>FactSales[TrackingID]</small><strong>{selected.includes('remove-tracking-id') ? 'Removed' : '11.8M distinct values'}</strong></span></article><article className={selected.includes('aggregation-table') ? 'is-fixed' : ''}><DatabaseZap /><span><small>Category query route</small><strong>{selected.includes('aggregation-table') ? 'Sales Agg · Import' : 'FactSales · detail scan'}</strong></span></article></div></section><section><p className="eyebrow">Report pressure</p><div className="mock-chart">{[82, 66, 48, 35].map((width, index) => <span key={width}><i style={{ width: `${selected.includes('category-grain') ? width : Math.min(98, width + 14)}%` }} /><b>{['Camping', 'Outerwear', 'Packs', 'Accessories'][index]}</b></span>)}</div><small>{selected.includes('reduce-interactions') ? 'This chart triggers one query.' : 'A selection triggers this chart plus three unused interactions.'}</small></section></div>
      <aside className="performance-observation" aria-live="polite"><Sparkles /><div><strong>{lastChanged ? optimizations.find((item) => item.id === lastChanged)!.title : 'Begin with the bottleneck you can explain'}</strong><p>{explainLastOptimization(lastChanged)}</p><small>{performanceAccuracyNote}</small></div></aside>
      <footer className="performance-links"><a href="#/lab/dax"><Sigma />Inspect DAX evaluation</a><a href="#/lab/storage-modes"><DatabaseZap />Compare storage modes</a><a href="https://learn.microsoft.com/en-us/training/modules/optimize-semantic-model-performance/" target="_blank" rel="noreferrer"><BookOpen />Microsoft Learn guidance</a></footer>
    </section>
  </main></div>;
}
