'use client';

import { ArrowLeft, ArrowRight, CalendarRange, Clock3, History, MapPin, RotateCcw, Table2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { evaluateScd, scdAccuracyNote, type ScdMode } from '@/engine/scd/time-machine';

export function ScdTimeMachine() {
  const [mode, setMode] = useState<ScdMode>('type2');
  const [changeApplied, setChangeApplied] = useState(false);
  const state = useMemo(() => evaluateScd(mode, changeApplied), [mode, changeApplied]);
  const chooseMode = (next: ScdMode) => { setMode(next); setChangeApplied(false); };

  return <div className="lab-page scd-page"><header className="lab-topbar"><a href="#explore" className="lab-back"><ArrowLeft />Fabric Atlas</a><div><strong>SCD Time Machine</strong><span>Aurora Outfitters · Customer 812</span></div><span className="simulation-label">Point-in-time model</span></header><main className="scd-shell">
    <section className="scd-controls" aria-labelledby="scd-heading"><p className="eyebrow">Historical change</p><h1 id="scd-heading">Move a customer without moving history</h1><p>Ava moves from Oslo to Bergen on 1 June. Choose how the dimension handles that change, then observe February and July sales.</p><fieldset><legend>Dimension behavior</legend><button className={mode === 'type1' ? 'active' : ''} onClick={() => chooseMode('type1')}><span>Type 1</span><strong>Overwrite current row</strong><small>Latest value only</small></button><button className={mode === 'type2' ? 'active' : ''} onClick={() => chooseMode('type2')}><span>Type 2</span><strong>Insert a new version</strong><small>Preserve point-in-time history</small></button></fieldset><div className="scd-action"><Button onClick={() => setChangeApplied(true)} disabled={changeApplied}><MapPin />Process June move <ArrowRight /></Button><Button variant="ghost" onClick={() => setChangeApplied(false)} disabled={!changeApplied}><RotateCcw />Reset time</Button></div><aside><History /><div><strong>{mode === 'type1' ? 'One business member, one row' : 'One business member, versioned rows'}</strong><p>{mode === 'type1' ? 'CustomerID and CustomerKey remain on the overwritten row.' : 'CustomerID remains the business key; each version receives a distinct surrogate CustomerKey.'}</p></div></aside></section>
    <section className="scd-stage" aria-labelledby="timeline-heading"><div className="scd-heading"><div><p className="eyebrow">Customer timeline</p><h2 id="timeline-heading">{changeApplied ? `${mode === 'type1' ? 'Overwrite' : 'Version'} applied` : 'Before the change load'}</h2></div><span>{changeApplied ? 'After 1 Jun 2026' : 'Before 1 Jun 2026'}</span></div><div className="scd-timeline"><div><strong>Jan</strong><i /><span>Oslo version active</span></div><div className="sale-marker feb"><b>$1,200 sale</b><small>14 Feb</small></div><div className={`change-marker ${changeApplied ? 'is-applied' : ''}`}><MapPin /><b>Moves to Bergen</b><small>1 Jun</small></div><div className={`sale-marker jul ${changeApplied ? 'is-visible' : ''}`}><b>$800 sale</b><small>8 Jul</small></div><div><strong>Aug</strong><i /><span>{changeApplied ? 'Bergen version active' : 'Change waiting'}</span></div></div>
      <div className="scd-tables"><section><header><Table2 /><strong>DimCustomer</strong><span>{state.versions.length} row{state.versions.length === 1 ? '' : 's'}</span></header><div className="scd-table-scroll"><table><thead><tr><th>CustomerKey</th><th>CustomerID</th><th>City</th><th>Valid from</th><th>Valid to</th><th>Current</th></tr></thead><tbody>{state.versions.map((row) => <tr className={`state-${row.state}`} key={row.customerKey}><td>{row.customerKey}</td><td>{row.customerId}</td><td>{row.city}</td><td>{row.validFrom}</td><td>{row.validTo}</td><td>{row.current ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div></section><section><header><Clock3 /><strong>FactSales resolution</strong><span>{state.sales.length} facts</span></header><div className="fact-resolution">{state.sales.map((sale) => <article key={sale.orderId}><span><small>Order #{sale.orderId} · {sale.date}</small><strong>${sale.revenue.toLocaleString()}</strong></span><ArrowRight /><span><small>CustomerKey {sale.customerKey}</small><strong>{sale.city}</strong></span></article>)}</div></section></div>
      <div className="scd-outcome"><section><span>Historical sales shown as Oslo</span><strong>${state.totals.Oslo.toLocaleString()}</strong></section><section><span>Historical sales shown as Bergen</span><strong>${state.totals.Bergen.toLocaleString()}</strong></section><aside aria-live="polite"><CalendarRange /><div><strong>{changeApplied ? mode === 'type1' ? 'Historical label changed' : 'Historical label preserved' : 'Change not processed'}</strong><p>{state.explanation}</p><small>{scdAccuracyNote}</small></div></aside></div>
    </section></main></div>;
}
